# Site wide configuration

title: "TwoTone"
description: An open-source web tool for generating sound from data
logo: /images/two-tone-logo.svg # 120x120 px default image used for Twitter summary card
logo-raster: /images/two-tone-logo.png
teaser: /images/400x250-placeholder.gif # 400x250 px default teaser image used in image archive grid
locale: en
timezone: America/New_York
url: https://twotone.io
feed:
  path: atom.xml
company: Datavized Technologies, Inc.
company-url: https://datavized.com

listing-site-teaser: false

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
# highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Default Front Matter values
defaults:
  -
    scope:
      path: "*.md" # an empty string here means all files in the project
    values:
      layout: "article"
  -
    scope:
      path: "*.html" # an empty string here means all files in the project
    values:
      layout: "article"

# Site owner
owner:
  name: Datavized
  email: contact@datavized.com
  social:
    twitter: datavized
    facebook: datavized
    instagram: datavized
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: /images/datavized-logo-square-blue.svg # 160x160 px image for author byline
  disqus-shortname:


include:
  # - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - CNAME
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - README.md
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - package-lock.json
  - spec
  - tmp
