# Site wide configuration

title: "TwoTone"
description: "This is a description of my awesome site."
logo: two-tone-logo.svg # 120x120 px default image used for Twitter summary card
teaser: 400x250-placeholder.gif # 400x250 px default teaser image used in image archive grid
locale: en
timezone: America/New_York
url: http://twotone.io
feed:
  path: atom.xml
company: Datavized Technologies, Inc.
company-url: https://datavized.com

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
# permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
# highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Datavized
  email: contact@datavized.com
  twitter: datavized
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


include:
  # - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
